### ISSUE TITLE
Firefox icon gets double lines in UI

### ISSUE THREAD

**Issue by RuudBurger** [NickSC/nzbFox#1]
Posted this in the addon comments, but better doing it here. 
![screen shot 2015-02-22 at 18 46 17](https://cloud.githubusercontent.com/assets/38136/6319955/63844484-bad1-11e4-80a6-b74ad5a37529.png)

Let me know what you need from me, I'm happy to test it out.

**Comment by NickSC** [comment]
What version of Firefox, and OS?

**Comment by RuudBurger** [comment]
OSX Yosemite and Firefox 35

**Comment by NickSC** [comment]
Fixed in 1.3.6
