### ISSUE TITLE
Newz-Complex.org - nzbFox remove passwords

### ISSUE THREAD

**Issue by BASF200** [NickSC/nzbFox#11]
Hello,

have found two other issues with newz-complex and nzbFox.

1. If you want to send NZBs who have a password behind the releasename {{password}} they get removed by nzbFox (only if you want to send nzbs from the browse-tables)

2. If you want to send NZBs direct from the tables the password will be sent with but nzbFox no longer recognize if the NZB is from the category series, movie ...

I love nzbFox, it is a really good addon to send nzbs to my sabnzbd installation and would say thank you for sharing and hope you can fix the above for NC.

regs

**Comment by NickSC** [comment]
>1. If you want to send NZBs who have a password behind the releasename {{password}} they get removed by nzbFox (only if you want to send nzbs from the browse-tables)

nzbFox does not alter release names, they are copied as-is from the browse table or details page. The {{password}} is not in the release name on the browse table, so it won't be passed. It seems Newz-Complex is only passing the password in the filenames, which is not provided on the details page. I'll see if I can scrape them from the URL.

>2. If you want to send NZBs direct from the tables the password will be sent with but nzbFox no longer recognize if the NZB is from the category series, movie ...

Sadly it is not possible for the download prompt to detect categories, you must manually specify a category (which was added in nzbFox 1.4.0). This applies to every indexer, not just Newz-Complex.

**Comment by BASF200** [comment]
Hello,

thank you for have a look about it.

In SabnzbD I have set up two categories, movies and TV. 
If I use the nzbFox button for sending a nzb to SabnzbD at the browse-tables nzbFox recognize if it is a movies or a series.

If I do this direct from the tables over the button nzbFox 
no longer recognizes it. 

regs

**Comment by NickSC** [comment]
Yeah I understand that, as I just explained it is not possible for the "direct" NZB download prompt to detect the category. That information is not passed to the download prompt window, only the NZB name is provided. The direct NZB method is meant for websites that aren't supported by the inline browser buttons.

**Comment by NickSC** [comment]
Password scraping has been implemented in nzbFox 1.4.1
