### ISSUE TITLE
Category Optional is used as a category as well

### ISSUE THREAD

**Issue by Panja0** [NickSC/nzbFox#12]
When downloading a nzb I choose "send to NZBget", when I do not choose a category and leave it on the default setting (Category Optional) the nzb is sent to NZBget and the category has been set to "Category Optional". Which of course is no category in NZBget. See screenshots below.

All the other categories work perfect! Nice to have them now named as my own categories. :)

<img width="446" alt="screenshot 2015-09-28 08 43 03" src="https://cloud.githubusercontent.com/assets/12939350/10129360/831cc2f2-65bd-11e5-839e-12910124cee8.png">
<img width="1363" alt="screenshot 2015-09-28 08 43 15" src="https://cloud.githubusercontent.com/assets/12939350/10129386/add053f6-65bd-11e5-84ef-ee2cebf3aa56.png">

**Comment by NickSC** [comment]
Woops! Thanks, fixed in next update.

**Comment by Panja0** [comment]
No problem mate! You're doing a great job. :) Thanks for the fast reply and help!

**Comment by Panja0** [comment]
Just downloaded the 1.4.1-fix release and I can confirm it's working!
No category is selected in NZBget when I send the NZB and leave it as "Category (optional)".

Thanks for the quick fix!

**Comment by NickSC** [comment]
No worries. I needed a reason to push another update to AMO anyway :)
