### ISSUE TITLE
UI broken in Nightly

### ISSUE THREAD

**Issue by nerotic** [NickSC/nzbFox#13]
You're probably aware of this but the icon is not displaying in 44.0a1.

**Comment by NickSC** [comment]
Thanks for the heads up. Repackaging using Jetpack 1.02 (released 6 days ago) fixed the issue, looks like FF 44 broke compatibility with the previous Jetpack release.

**Comment by nerotic** [comment]
And thank you for making me aware of the some of the issues surrounding
nzbs.in.  Since I don't really participate in the forums or read up on them
anywhere else I wasn't aware of some of the issues surrounding them.

I've since signed up for a lifetime account at nzb.is which was a bargain
and my completion rate has jumped quite a bit.

**Comment by NickSC** [comment]
Oh, thank you for the review :)
If you're quick, you can sign up for a DogNZB account - registrations are currently open. DogNZB and NZBs.org are the best indexers, in my opinion.

https://dognzb.cr/login.cfm

**Comment by NickSC** [comment]
(wrong link - https://dognzb.cr/login.cfm?r)

**Comment by nerotic** [comment]
Is it possible they already closed them?

We understand your desire to check if registrations are open. But excessive
hammering is not tolerated and your IP address has been blacklisted. Limit
your registration checks to reasonable intervals and the restriction will
lift automatically.

**Comment by NickSC** [comment]
They are still open. Your IP has been blacklisted though as the message suggests, if you are using a VPN or Proxy etc that might be why. You just need to change IP, by changing VPN server for example.

**Comment by nerotic** [comment]
I wasn't using my VPN but I flipped it on...I'm registered now :)

Thanks for the heads up.

**Comment by nerotic** [comment]
BTW...where can I download the latest version?

**Comment by NickSC** [comment]
You will automatically download updates from addons.mozilla.org once an update is released
