### ISSUE TITLE
Sending NZBs from nzindex.nl to sabnzbd does not work correctly

### ISSUE THREAD

**Issue by ralle12345** [NickSC/nzbFox#15]
When I send a link via the button inserted into the page, some mechanism fills not only the file/nzb-name, but also the password field, which is annoying, when you paste a string including the nzb-name as well as the password enclosed in {{}}.

**Comment by NickSC** [comment]
Please provide some examples, as your issue is not clear

**Comment by ralle12345** [comment]
When searching for the file "ZB35wD26y9VMM6uQgdfiKXd4nHn0yZ" on nzbindex and sending it to sabnzbd this is what it looks like in sabnzbd:
![sabnzb](https://cloud.githubusercontent.com/assets/12152388/12179190/bdd5681a-b575-11e5-962c-14b7c3128fd5.jpg)

It seems like the part in font of the "/" in the description gets pushed to the filename field while the part behind it goes to the password field.

**Comment by NickSC** [comment]
Fixed in next update
