### ISSUE TITLE
Sending NZBs from binsearch.info to sabnzb sends the wrong NZB

### ISSUE THREAD

**Issue by ralle12345** [NickSC/nzbFox#16]
Sending http://binsearch.info/?q=ZB35wD26y9VMM6uQgdfiKXd4nHn0yZ&max=100&adv_age=1100&server=2 to Sabnzb leads to this NZB in the Queue:

    <?xml version="1.0" encoding="iso-8859-1" ?>
    <!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.0//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.0.dtd">
    
    <nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
    
    <file poster="dravenus20 &lt;dravenus20@yahoo.com&gt;" date="1428788221" subject="&quot;Lore (2012)(dvd9)(Nl subs) RETAIL SAM TBS .zip&quot; yEnc (1/1)">
    <groups><group>alt.binaries.misc</group></groups>
    <segments>
    <segment bytes="21087"     number="1">F8nfu2LqxCqNaYM54SnM_7033o13411@JBinUp.local</segment>
    </segments>
    </file>
    </nzb>

which is definitely some other file than the one in the search.

**Comment by NickSC** [comment]
Fixed in next update

**Comment by ralle12345** [comment]
Do you have a schedule when the next version will be available?

**Comment by NickSC** [comment]
I can't give a schedule, it all depends on when Mozilla approves updates. It can take a very long time, sometimes a few hours.

**Comment by ralle12345** [comment]
I just asked because I didn't see ans source changes in the git repo.
