### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Tangfolio** [NickSC/nzbFox#17]
Hi, Just installed nzbFox in Firefox and wondering if there is any help documentation for it anywhere as I can't get it to do anything.

**Comment by NickSC** [comment]
There is no documentation, because use is simple - you install it, an icon appears in the addon toolbar just like every other addon. Click on it and it will open the addon settings page, its very self explanatory.

What exactly are you having trouble doing?

**Comment by Tangfolio** [comment]
Thanks for your quick reply. It opens the page when I click on the icon but it isn't explaining it's self to me at all. I get a list of all the things it is supposed to do but how do I get it to do them, I have SABnzbd running and I have left all the settings on their default but there are still no signs of it doing anything. Several screen shots appear to be shown on https://addons.mozilla.org/en-US/firefox/addon/nzbfox/ but I don't get anything like that, all I keep getting is the add-ons page and no sign of anything else.

**Comment by NickSC** [comment]
That means you have not enabled SABnzbd+ in the options window.

You must tick "Enable SABnzbd+" and also fill in the URL to SAB and its API key

**Comment by Tangfolio** [comment]
Thanks, got a SABnzbd+ download speed window coming up now when I click on the icon.
How do the integrated indexers work, tried going to a couple of the sites listed but don't see anything going on. Selected 'send nzb to sabnzbd' but nothing different happens if I click on an nzb download link, I have set firefox to download nzb's automatically without any interaction, is that the problem?

**Comment by NickSC** [comment]
If you click the inline buttons on search results, the NZB will go directly to SAB.
Make sure you have categories set up correctly, they must match with your categories in SABnzbd. Also make sure nzbFox can actually connect to sab by clicking the 'Test SABnzbd+' button in the options window.

**Comment by Tangfolio** [comment]
OK, thanks, test works but haven't bothered with categories in SABnzbd so will forget about that.

**Comment by NickSC** [comment]
If you haven't got a category set in SAB, just make it empty in the nzbFox settings and it should go to the default category.
