### ISSUE TITLE
Password Issues with Newz-Complex

### ISSUE THREAD

**Issue by DankoJones** [NickSC/nzbFox#20]
Hello,

newz-complex has changed their passwords before some time. The Passwords now include special characters: ] @ ~ [

nzbFox can not pass the symbols for nzbget or Sabnzbd. The symbols get replaced by a %
Can you customize this in nzbFox please ?

Best Regs

**Comment by NickSC** [comment]
Thank you for the report, this will be fixed in the next nzbFox update.
