### ISSUE TITLE
Error parsing file file no content when using nzbfox.

### ISSUE THREAD

**Issue by jimpc** [NickSC/nzbFox#24]
Been using nzbfox for a couple weeks. Today any nzb sent to nzbget via nzbfox get the error, "error parsing file file no content." When downloading the nzb by traditional methods straight to the expected folder in nzbget it works fine.

**Comment by NickSC** [comment]
Without any useful information such as nzbget version, debug logs, method being used (inline button or download dialog), indexer, etc, there's not much I can do to check this. It does not appear to be affecting anyone else currently.
