### ISSUE TITLE
newz-complex.org not working

### ISSUE THREAD

**Issue by mrpi** [NickSC/nzbFox#3]
I added "newz-complex.org" as a "Personal Newznab Indexer" in the settings, but this did not work.

The root address for api requests on this site is "http://newz-complex.org/www/". It seems, that sub urls are not supported.

nzbFox sends nzbs like these to SABnzb: http://newz-complex.org/api?t=get&id=getnzb...
But it should create this: http://newz-complex.org/www/api?t=get&id=getnzb...

Inserting "newz-complex.org/www" as a "Personal Newznab Indexer" seems not to fix the problem. nzbFox did not blend in its special buttons on this page, if I do so.

**Comment by NickSC** [comment]
Thanks for the report. I can confirm the issue - shall have it fixed in the next update.
In the mean time, assuming that is your own personal indexer, you could perform a HTTP redirect on `/api` to the correct `/www/api` URL, SAB should follow the redirect.

**Comment by BASF200** [comment]
Hello,
have found two other issues with newz-complex and nzbFox.

1. If you want to send NZBs who have a password behind the releasename {{password}} they are removed by nzbFox (only from the browse-tables)

2. If you want to send NZBs direct from the tables the password will be sent with but nzbFox no longer recognize if the NZB is from the category series, movie ...

I love nzbFox, it is a really good addon to send nzbs to my sabnzbd installation and would say thank you for sharing.

regs

**Comment by NickSC** [comment]
Please create a new issue report for unrelated issues.
