### ISSUE TITLE
Empty NZB files

### ISSUE THREAD

**Issue by marthiel** [NickSC/nzbFox#4]
Empty NZB file api?t=get&id=15c3395fde7ec952df0cd&apikey=snip.nzb [https://api.nzb.su/api?t=get&id=15c3395fd3a52df0cd&apikey=snip]

I tryed multiple nzb files and they all have that error message when i use nzbFox to send them to sabnzb. Any idea?

**Comment by NickSC** [comment]
The NZB.su API is currently down. Clicking the link will tell you `502 Bad Gateway`

**Comment by marthiel** [comment]
Thank you for the clarification!

----- Ursprüngliche Nachricht -----
Von: "Enesce" <notifications@github.com>
Gesendet: ‎14.‎04.‎2015 14:41
An: "NickSC/nzbFox" <nzbFox@noreply.github.com>
Cc: "marthiel" <Mario.a.thiel@gmail.com>
Betreff: Re: [nzbFox] Empty NZB files (#4)

The NZB.su API is currently down. Clicking the link will tell you 502 Bad Gateway
