### ISSUE TITLE
UI broken in Nightly

### ISSUE THREAD

**Issue by nerotic** [NickSC/nzbFox#5]
![n7zq583zbfkxc4iiszmgun7bu8qieekcmzuyhcmhl8u](https://cloud.githubusercontent.com/assets/487809/7602452/0b24b76e-f925-11e4-96cc-da6a8b7d3998.jpg)

**Comment by NickSC** [comment]
This is now fixed in nzbFox 1.3.8
https://addons.mozilla.org/en-US/firefox/addon/nzbfox/versions/1.3.8

Thanks for the report :)
