### ISSUE TITLE
Support for https://www.nzbindex.com

### ISSUE THREAD

**Issue by sioban** [NickSC/nzbFox#6]
Hi,

I'm using the ssl (https) version of nzbindex.
Your script works on https://www.nzbindex.nl but not on https://www.nzbindex.com.

The problem with .nl extension is that the SSL certificate is wrong (it's the same for nzbindex.com and nzbindex.nl), so sabNZBdplus does not want to connect to https://www.nzbindex.nl (it works great with https://www.nzbindex.com).

If you just support .com version of nzbindex, it would be a lot simplier for us using the https version of this website (I do not want to connect using unsecure http when I'm on wifi or not at home).

**Comment by NickSC** [comment]
I have just published version 1.3.9 which adds support for `*.nzbindex.com`

**Comment by sioban** [comment]
Nice, thank you !
