### ISSUE TITLE
No nzbget option in nzbfox

### ISSUE THREAD

**Issue by tuckson** [NickSC/nzbFox#7]
Hi

On the site dutplanet.net I try to download nzb's with nzbfox. nzbget can be reached, testbutton in options gives a success message. However when Ik try to download an nzb file, no nzbget option is given
![nzbfox](https://cloud.githubusercontent.com/assets/13397674/8763505/916c5940-2d9f-11e5-960e-264899a4122b.png)

**Comment by NickSC** [comment]
Firefox 39+ removed functions that were required for me to add the "Send to ____" options to the download dialog.

I am currently working on a fix for this issue and should have it on addons.mozilla.org soon.

**Comment by NickSC** [comment]
This is now fixed in version 1.3.10
