### ISSUE TITLE
Downloaded NZB's are not redirected to NZBGet

### ISSUE THREAD

**Issue by Panja0** [NickSC/nzbFox#8]
When downloading NZB's they won't get forwarded to my NZBGet server. 
I press download NZB, the Firefox download manager pops up and I choose "send to NZBGet".
The NZB's are downloaded but are not being received by my NZBGet server.

The index sites (nzbindex.com, binsearch) are all working ok.
Connection tests to my NZBGet server are working as well.

Apple MacBook Pro
OSX 10.10.4
Firefox 39.0.3
nzbFox 1.3.10

**Comment by NickSC** [comment]
What version of NZBGet are you using?

When you say the other index sites (binsearch etc) are all working ok, are you referring to the same download manager "Send to NZBGet" option, or the little download buttons next to search results?

Do you see any errors about it in the NZBGet logs?
Is the .nzb file deleted from your Downloads directory once it is meant to have been sent?

**Comment by Panja0** [comment]
NZBGet v15 (latest stable)

I'm talking about the little button next to the search results, that works. 
Download Manager "send to NZBGet" is NOT working.
Nope, nothing to see in the logs... So I think it NZB just doesn't get sent to the NZBGet server.

**Comment by Panja0** [comment]
Any news on this issue?

**Comment by NickSC** [comment]
Sorry, I have tested on the same software versions you specified and was not able to reproduce the issue at all. I'm afraid there is nothing I can do at the moment, will have to wait and see if I get similar reports.

**Comment by Panja0** [comment]
Do you have a Mac as well? I'm using it on OSX 10.10.5

**Comment by NickSC** [comment]
Yes, I test on Yosemite 10.10 & Mountain Lion 10.8 via Virtual Machine, and both are working.
Would you be able to test using Sabnzbd? I'm not sure where else to look other than NZBGet configuration.

**Comment by Panja0** [comment]
The problem is that I have ditched my SabNZBD install a few weeks ago.
Could it be a problem that I don't use a watched folder in NZBget?

**Comment by NickSC** [comment]
A watched folder is not required, the .NZB file is uploaded directly to NZBGet via API. Is the .nzb file removed from your Downloads folder?

**Comment by Panja0** [comment]
Ok...
No it's not deleted from the downloads folder.
So I think it's not forwarded correctly.

Though when pressing a link in one of the supported websites (like binsearch) it works without any problem!

**Comment by NickSC** [comment]
Try change the `Connection Timeout` value in the nzbFox preferences page. Default value is 1 second, try changing it to something higher like 10 seconds. If the NZB file you are uploading is large, it might be taking too long and causing a connection timeout.

If that fails, tick the 'Developer Mode' checkbox in nzbFox preferences.
Type `about:config` in your URL bar and hit enter
Once that has loaded, right click and select `New > String`
Name: `extensions.sdk.console.logLevel`
Value: `info`
Restart browser. Hit Command+Shift+J and a Browser Console will open.

Try send an NZB to NZBGet and see what shows up in the console, you should be able to see several lines from nzbFox. things like `parseQueue(nzbg)`

**Comment by Panja0** [comment]
[code]Download prompt detected, MIME = "application/x-nzb" suggestedFileName = "bb03-amd64-final.par2.nzb" main.js:37
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.6.33
Vendor: Intel
Renderer: Intel(R) Iris(TM) Graphics 6100
FBO Texture Target: TEXTURE_2D
-------- Download Detected -------- main.js:37
CLI = nzbg main.js:37
Path = /Users/panja/Downloads/bb03-amd64-final.par2.nzb main.js:37
Title	= bb03-amd64-final.par2.nzb main.js:37
too many function arguments base64.js:41:0
parseHistory(nzbg), items = 0 main.js:37[/code]

**Comment by NickSC** [comment]
Hmm, `too many function arguments base64.js:41:0` is the issue. Which is strange because the function only has 1 arguement.

You should be able to click on the `base64.js` part and it will open up that file and the error line, can you screenshot it?

**Comment by Panja0** [comment]
http://i.imgur.com/nPSUwxn.png
http://pastebin.com/dkAjMwfh

Screenshot + pastebin
:)

**Comment by NickSC** [comment]
Can you try this version of nzbFox? Drag it onto the Firefox window, click Install, then try send an NZB.

https://www.dropbox.com/s/fwsrmzx6adnwhqh/nzbfox.dev.xpi?dl=0

**Comment by Panja0** [comment]
Working!
Thanks! :+1: 

What was the problem?
Of is it to developer'ish talk?

**Comment by NickSC** [comment]
I'm not 100% sure what the problem there is, as the base64.js file you linked is the same as mine. I changed it to directly call the `atob` function instead of going through the base64.js `encode` function. It's a messy solution though, can you test if this one works too?

https://www.dropbox.com/s/fwsrmzx6adnwhqh/nzbfox.dev.xpi?dl=0

(same link as before, but file was updated slightly)

**Comment by Panja0** [comment]
Seems to be working as well! :+1: 
Is it better to use the latter build?

**Comment by NickSC** [comment]
yeah use the latter build, if you find any issues with NZB failing, let me know ASAP as I plan on releasing this build fairly soon.

**Comment by Panja0** [comment]
Thanks Nick! Appreciated. :+1: 

Will let you know if I run into any troubles.
Cheers!

**Comment by NickSC** [comment]
You're welcome :)

(Side note, I find it funny that the error is 'too many function arguments', yet its fixed by adding more arguments)

**Comment by Panja0** [comment]
LOL!
That's indeed a bit odd...

Well I'm a happy camper once again.

**Comment by NickSC** [comment]
1.4.0 is released, make sure you upgrade to the official version by downloading nzbFox from https://addons.mozilla.org/en-US/firefox/addon/nzbfox/versions/1.4.0

**Comment by Panja0** [comment]
Awsome! Already downloaded and I can confirm it working.
Category addition is awesome! Though I have a feature request. Will submit a new "issue" for this.

Thanks for your hard work!
