### ISSUE TITLE
Unable to connect with Firefox 40+

### ISSUE THREAD

**Issue by ragingsheep** [NickSC/nzbFox#9]
Trying to connect to nzbget on Firefox 40 results in the following error: 

Unable to connect
http://nzbget:tegbzn6789@127.0.0.1:6789/jsonrpc

the '/jsonrpc' is appended onto the end regardless of the actual address used.

**Comment by NickSC** [comment]
`/jsonrpc` is a standard part of the NZBGet API, so it is intended to be added to the end.

What happens when you copy paste that URL into your browser?

**Comment by ragingsheep** [comment]
I'm back onto to Firefox 39.0.3 which doesn't have the issue. Seems like something happened between that at 40.0.2. 

Also should note that if I click on the button at the bottom right of the popup (see pic), then it will correctly bring up nzbget. 

[pic](https://cloud.githubusercontent.com/assets/13818323/9293006/51eeac0a-445b-11e5-88c9-20518ede796c.jpg)

**Comment by ragingsheep** [comment]
Ok, looks like it was only affecting fresh installs of FF40.0.2. 

Having it working on 39.0.3 and then updating to 40.0.2 means that it still works.

**Comment by NickSC** [comment]
Ok thanks for the info, I will look into it.
